### ISSUE TITLE
Mouseover Problem

### ISSUE THREAD

**Issue by Gorira-Banana** [Gorira-Banana/hackathon#1]
## overview

正誤判定がパズルからマウスポインタがはなれた時に行いたい。現在はパズルのマスごとに判定が行われている。

**Comment by yui1308** [comment]
とりあえず…  
マウスポインタがパズルから離れたときに判定を行うようにしました。  
今はマウスがパズル上にあるときは「判定中」と出ます。  
（main.jsとmain.htmlを編集しました）

**Comment by Gorira-Banana** [comment]
修正しました。
